language: node_js
node_js:
  - "stable"
cache:
  directories:
    - ~/.npm
    - node_modules
    - .cache
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: public
  keep-history: true
  on:
    branch: master
before_script:
  - "yarn global add gatsby"
  - "yarn"
script:
  - "yarn build"
notifications:
  email:
    recipients:
      - navstyachka@gmail.com
    on_success: always
    on_failure: always
