import React from 'react';

import Layout from '../components/Layout';

export default () => (
  <Layout>
    <h2 className="text-3xl mb-4">Hello World.</h2>
    <p>
      You are looking at index generated by src/pages/index.js.
      <br />
      By default, this page does not query anything from Contentful.
      <br />
      You can still load CMS content by
    </p>
    <blockquote className="font-mono text-sm text-blue-600 m-4">{"import {QueryStatic} from 'gatsby'"}</blockquote>
    <p>Please check Gatsby documentation for more information.</p>
  </Layout>
);
