import React from 'react';
import eventbriteSDK from 'eventbrite';
import Layout from '../components/Layout';

const sdk = eventbriteSDK({ token: 'QKUVGWF3QEJRE6LHPKSD' });

export default () => {
  sdk.request('/users/me').then(res => {
    console.log(res);
  });

  return (
    <Layout>
      <h2 className="text-3xl mb-4">Hello World.</h2>
      <p>
        You are looking at index generated by src/pages/index.js.
        <br />
        By default, this page does not query anything from Contentful.
        <br />
        You can still load CMS content by
      </p>
      <blockquote className="font-mono text-sm text-blue-600 m-4">{"import {QueryStatic} from 'gatsby'"}</blockquote>
      <p>Please check Gatsby documentation for more information.</p>
    </Layout>
  );
};
